### ISSUE TITLE
Game crashes on window close

### ISSUE THREAD

**Issue by tnibert** [tnibert/Panzer-Deathmatch-3D-Godot#17]
When we close the game window, we receive the following error:
```
$ ./test4.x86_64 
OpenGL ES 3.0 Renderer: GeForce 940MX/PCIe/SSE2
Joining network
Connection established
/root/GUI/Map
/root/GUI
[KinematicBody:1746]

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
/proc/self/maps:
00400000-03001000 r-xp 00000000 08:0a 7507470                            /home/tim/code/godot-3d-learn/test4.x86_64
03201000-03289000 r--p 02c01000 08:0a 7507470                            /home/tim/code/godot-3d-learn/test4.x86_64
03289000-0329b000 rw-p 02c89000 08:0a 7507470                            /home/tim/code/godot-3d-learn/test4.x86_64
0329b000-032af000 rw-p 00000000 00:00 0 
037a0000-0a53a000 rw-p 00000000 00:00 0                                  [heap]
40513000-405b4000 rw-p 00000000 00:00 0 
406c4000-406c6000 r-xs 00000000 08:08 8519729                            /tmp/.gldOmvV1 (deleted)
40b34000-40b44000 rwxp 00000000 00:00 0 
416d0000-416e0000 rwxp 00000000 00:00 0 
41c11000-41c61000 rwxp 00000000 00:00 0 
7fc9c4000000-7fc9c4021000 rw-p 00000000 00:00 0 
7fc9c4021000-7fc9c8000000 ---p 00000000 00:00 0 
7fc9c93ff000-7fc9c97ff000 rw-s 00000000 00:06 582                        /dev/nvidiactl
7fc9cc000000-7fc9cc021000 rw-p 00000000 00:00 0 
7fc9cc021000-7fc9d0000000 ---p 00000000 00:00 0 
7fc9d0000000-7fc9d0021000 rw-p 00000000 00:00 0 
7fc9d0021000-7fc9d4000000 ---p 00000000 00:00 0 
7fc9d47a7000-7fc9d4ba7000 rw-s 00000000 00:06 582                        /dev/nvidiactl
7fc9d6ba8000-7fc9d6fff000 rw-p 00000000 00:00 0 
7fc9d7200000-7fc9d7400000 rw-s 00000000 00:06 582                        /dev/nvidiactl
7fc9d7800000-7fc9d8000000 rw-p 00000000 00:00 0 
7fc9d8000000-7fc9d8021000 rw-p 00000000 00:00 0 
7fc9d8021000-7fc9dc000000 ---p 00000000 00:00 0 
7fc9dc0fe000-7fc9dc1fe000 rw-s 00000000 00:06 582                        /dev/nvidiactl
7fc9dc1fe000-7fc9dc1ff000 ---p 00000000 00:00 0 

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x7fc9f962a8a9):0x7fc9f962a899  1f 84 00 00 00 00 00 64 48 8b 04 25 40 fe ff ff  .......dH..%@...
0x7fc9f962a8a9  ff a0 60 10 00 00 0e 00 00 0f 1f 40 00 66 2e 0f  ..`........@.f..
0x7fc9f962a8b9  1f 84 00 00 00 00 00 64 48 8b 04 25 40 fe ff ff  .......dH..%@...
0x7fc9f962a8c9  ff a0 60 10 00 00 0e 00 00 0f 1f 40 00 66 2e 0f  ..`........@.f..

=================================================================
	Native stacktrace:
=================================================================
	0x7fc9fba73478 - /usr/lib/libmonosgen-2.0.so.1 : (null)
	0x7fc9fba083d4 - /usr/lib/libmonosgen-2.0.so.1 : (null)
	0x7fc9fb97b468 - /usr/lib/libmonosgen-2.0.so.1 : (null)
	0x7fc9fb319890 - /lib/x86_64-linux-gnu/libpthread.so.0 : (null)
	0x7fc9f962a8a9 - /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 : (null)

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x7fc9fddcd840 from 0x7fc9ddd8b700
Entering thread summarizer pause from 0x7fc9ddd8b700
Finished thread summarizer pause from 0x7fc9ddd8b700.

Waiting for dumping threads to resume

Debug info from gdb:


=================================================================
	External Debugger Dump:
=================================================================
[New LWP 13597]
[New LWP 13599]
[New LWP 13600]
[New LWP 13601]
[New LWP 13602]
[New LWP 13603]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fc9fb3178c2 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fff4a984500, expected=0, futex_word=0xa23b7e0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
205	../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7fc9fddcd840 (LWP 13596) "test4.x86_64" 0x00007fc9fb3178c2 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fff4a984500, expected=0, futex_word=0xa23b7e0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  2    Thread 0x7fc9fddcc700 (LWP 13597) "test4.x86_64" 0x00007fc9fb3176d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x3843158) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0x7fc9f3f41700 (LWP 13599) "test4.x86_64" 0x00007fc9fb3176d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x3ba2c98) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0x7fc9ddeee700 (LWP 13600) "test4.x86_64" 0x00007fc9fb318c60 in __GI___nanosleep (requested_time=0x7fc9ddeedcb0, remaining=0x7fc9ddeedcb0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  5    Thread 0x7fc9ddead700 (LWP 13601) "test4.x86_64" 0x00007fc9fa6bb9d0 in __GI___nanosleep (requested_time=requested_time@entry=0x7fc9ddeaccc0, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  6    Thread 0x7fc9dd3ff700 (LWP 13602) "SGen worker" 0x00007fc9fb3149f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fc9fbf9f508) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  7    Thread 0x7fc9ddd8b700 (LWP 13603) "Finalizer" 0x00007fc9fb31923a in __waitpid (pid=13674, stat_loc=0x7fc9fdc5cc04, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30

Thread 7 (Thread 0x7fc9ddd8b700 (LWP 13603)):
#0  0x00007fc9fb31923a in __waitpid (pid=13674, stat_loc=0x7fc9fdc5cc04, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007fc9fba736c8 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#2  0x00007fc9fba083d4 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#3  0x00007fc9fb97b468 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#4  <signal handler called>
#5  0x00007fc9f962a8a9 in ?? () from /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0
#6  0x000000000168bd45 in RasterizerStorageGLES3::free (this=0x3ba5df0, p_rid=...) at drivers/gles3/rasterizer_storage_gles3.cpp:7398
#7  0x00000000022c4b1c in VisualServerRaster::free (this=0x38de5e0, p_rid=...) at servers/visual/visual_server_raster.cpp:72
#8  0x000000000230eaf8 in VisualServerWrapMT::free (this=0x3bfd300, p1=...) at servers/visual/visual_server_wrap_mt.h:580
#9  0x0000000001ee23df in Material::~Material (this=0xa082ee0, __in_chrg=<optimized out>) at scene/resources/material.cpp:101
#10 0x0000000001f02e4d in SpatialMaterial::~SpatialMaterial (this=0xa082ee0, __in_chrg=<optimized out>) at scene/resources/material.cpp:2352
#11 0x0000000000e98702 in memdelete<Reference> (p_class=0xa082ee0) at ./core/os/memory.h:120
#12 0x0000000001421f7f in godot_icall_Reference_Disposed (p_obj=0x7fc9fdd58568, p_ptr=0xa082ee0, p_is_finalizer=true) at modules/mono/glue/base_object_glue.cpp:103
#13 0x0000000041c5d025 in ?? ()
#14 0x00007fc9fdd58568 in ?? ()
#15 0x00007fc9ddd8aa70 in ?? ()
#16 0x0000000004c79b80 in ?? ()
#17 0x00000000050c11fb in ?? ()
#18 0x00007fc9fdd58568 in ?? ()
#19 0x00007fc9fdd58568 in ?? ()
#20 0x00007fc9fbf8b168 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#21 0x00007fc9fbf8b170 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#22 0x00007fc9cc002820 in ?? ()
#23 0x00007fc9ddd8aa70 in ?? ()
#24 0x00007fc9ddd8a9b0 in ?? ()
#25 0x0000000041c5ace0 in ?? ()
#26 0x0000000004d53920 in ?? ()
#27 0x00007fc9fbf8b168 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#28 0x00007fc9fbf8b170 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#29 0x0000000000000000 in ?? ()

Thread 6 (Thread 0x7fc9dd3ff700 (LWP 13602)):
#0  0x00007fc9fb3149f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fc9fbf9f508) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7fc9fbf9f520, cond=0x7fc9fbf9f4e0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7fc9fbf9f4e0, mutex=0x7fc9fbf9f520) at pthread_cond_wait.c:655
#3  0x00007fc9fbc241da in ?? () from /usr/lib/libmonosgen-2.0.so.1
#4  0x00007fc9fb30e6db in start_thread (arg=0x7fc9dd3ff700) at pthread_create.c:463
#5  0x00007fc9fa6f888f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fc9ddead700 (LWP 13601)):
#0  0x00007fc9fa6bb9d0 in __GI___nanosleep (requested_time=requested_time@entry=0x7fc9ddeaccc0, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007fc9fa6ee877 in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#2  0x0000000000e7254b in JoypadLinux::monitor_joypads (this=0x45ce500) at platform/x11/joypad_linux.cpp:217
#3  0x0000000000e7244c in JoypadLinux::run_joypad_thread (this=0x45ce500) at platform/x11/joypad_linux.cpp:115
#4  0x0000000000e7242f in JoypadLinux::joy_thread_func (p_user=0x45ce500) at platform/x11/joypad_linux.cpp:102
#5  0x0000000001638db4 in ThreadPosix::thread_callback (userdata=0x45df5d0) at drivers/unix/thread_posix.cpp:70
#6  0x00007fc9fb30e6db in start_thread (arg=0x7fc9ddead700) at pthread_create.c:463
#7  0x00007fc9fa6f888f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fc9ddeee700 (LWP 13600)):
#0  0x00007fc9fb318c60 in __GI___nanosleep (requested_time=0x7fc9ddeedcb0, remaining=0x7fc9ddeedcb0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000000001634ca5 in OS_Unix::delay_usec (this=0x7fff4a984700, p_usec=1000) at drivers/unix/os_unix.cpp:276
#2  0x000000000163dd66 in AudioDriverPulseAudio::thread_func (p_udata=0x7fff4a984b40) at drivers/pulseaudio/audio_driver_pulseaudio.cpp:507
#3  0x0000000001638db4 in ThreadPosix::thread_callback (userdata=0x453fa40) at drivers/unix/thread_posix.cpp:70
#4  0x00007fc9fb30e6db in start_thread (arg=0x7fc9ddeee700) at pthread_create.c:463
#5  0x00007fc9fa6f888f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fc9f3f41700 (LWP 13599)):
#0  0x00007fc9fb3176d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x3ba2c98) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x3ba2c98, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fc9fb3177c8 in __new_sem_wait_slow (sem=0x3ba2c98, abstime=0x0) at sem_waitcommon.c:181
#3  0x0000000001638ab2 in SemaphorePosix::wait (this=0x3ba2c90) at drivers/unix/semaphore_posix.cpp:41
#4  0x00000000022d612d in VisualServerScene::_gi_probe_bake_thread (this=0x7fc9f3f42020) at servers/visual/visual_server_scene.cpp:2504
#5  0x00000000022d4f26 in VisualServerScene::_gi_probe_bake_threads (self=0x7fc9f3f42020) at servers/visual/visual_server_scene.cpp:2290
#6  0x0000000001638db4 in ThreadPosix::thread_callback (userdata=0x3ba5ba0) at drivers/unix/thread_posix.cpp:70
#7  0x00007fc9fb30e6db in start_thread (arg=0x7fc9f3f41700) at pthread_create.c:463
#8  0x00007fc9fa6f888f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fc9fddcc700 (LWP 13597)):
#0  0x00007fc9fb3176d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x3843158) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x3843158, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fc9fb3177c8 in __new_sem_wait_slow (sem=0x3843158, abstime=0x0) at sem_waitcommon.c:181
#3  0x0000000001638ab2 in SemaphorePosix::wait (this=0x3843150) at drivers/unix/semaphore_posix.cpp:41
#4  0x000000000268efc4 in _IP_ResolverPrivate::_thread_function (self=0x3842bb0) at core/io/ip.cpp:101
#5  0x0000000001638db4 in ThreadPosix::thread_callback (userdata=0x3843190) at drivers/unix/thread_posix.cpp:70
#6  0x00007fc9fb30e6db in start_thread (arg=0x7fc9fddcc700) at pthread_create.c:463
#7  0x00007fc9fa6f888f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fc9fddcd840 (LWP 13596)):
#0  0x00007fc9fb3178c2 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fff4a984500, expected=0, futex_word=0xa23b7e0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0xa23b7e0, abstime=abstime@entry=0x7fff4a984500) at sem_waitcommon.c:111
#2  0x00007fc9fb3179d3 in __new_sem_wait_slow (sem=0xa23b7e0, abstime=0x7fff4a984500) at sem_waitcommon.c:181
#3  0x00007fc9fbbd49ec in mono_domain_finalize () from /usr/lib/libmonosgen-2.0.so.1
#4  0x0000000000fbcc6d in GDMono::_unload_scripts_domain (this=0x4c851b0) at modules/mono/mono_gd/gd_mono.cpp:712
#5  0x0000000000fbd41a in GDMono::~GDMono (this=0x4c851b0, __in_chrg=<optimized out>) at modules/mono/mono_gd/gd_mono.cpp:946
#6  0x0000000001216797 in memdelete<GDMono> (p_class=0x4c851b0) at ./core/os/memory.h:120
#7  0x000000000120c00d in CSharpLanguage::finish (this=0x4b43c40) at modules/mono/csharp_script.cpp:146
#8  0x000000000253256f in ScriptServer::finish_languages () at core/script_language.cpp:130
#9  0x0000000000e96718 in Main::cleanup () at main/main.cpp:1993
#10 0x0000000000e5bc88 in main (argc=1, argv=0x7fff4a984e78) at platform/x11/godot_x11.cpp:56
ERROR: _unload_scripts_domain: Mono: Domain finalization timeout
   At: modules/mono/mono_gd/gd_mono.cpp:713.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at Godot.Object:godot_icall_Reference_Disposed <0x000a4>
	  at Godot.Object:Dispose <0x0017f>
	  at Godot.Object:Finalize <0x00077>
	  at System.Object:runtime_invoke_virtual_void__this__ <0x0015d>
=================================================================
Aborted (core dumped)

````
This doesn't have any effect on gameplay.  However, when we exit the game, we should exit cleanly.

**Comment by tnibert** [comment]
Not observed since upgrading to Godot 3.1 stable.  Resolved.
